---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base and CLI packages
  ansible.builtin.apt:
    name:
      # --- base ---
      - snap
      - git
      - curl
      - lynx
      - wget
      - vim
      - gedit
      - gnome-tweaks
      # - caffeine
      - htop
      - unzip
      - ca-certificates
      - gnupg
      - lsb-release
      - build-essential
      - software-properties-common
      - util-linux-extra
      - zram-config

      # --- CLI tools ---
      - tree
      - jq
      - ripgrep
      - fd-find
      - bat
      - fzf
      - ncdu
      - tealdeer
    state: present
    install_recommends: false

- name: Install ChatGPT desktop
  ansible.builtin.snap:
    name: chatgpt-desktop